# - name: Adguard Home.Download - Download AdGuard
#   get_url:
#     url: "{{ adguard_download_url }}"
#     dest: "{{ adguard_download_dest }}"
#     mode: '0440'

- name: Create target installation directory
  file:
    path: "{{ adguard_install_dest }}"
    state: directory
    mode: 0755
    owner: "{{ adguard_user }}"
    group: "{{ adguard_group }}"

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{ adguard_download_url }}"
    dest: "{{ adguard_install_dest }}"
    owner: "{{ adguard_user }}"
    group: "{{ adguard_group }}"
    remote_src: yes