- name: Deploy AdGuard Home service file
  template:
    src: adguard.service.j2
    dest: /etc/systemd/system/adguard.service
    owner: root
    group: root
    mode: 0755

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

- name: Start and Enable adguard
  service:
    name: adguard
    state: started
    enabled: True